/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountDetailsDialog: typeof import('./src/components/management/AccountDetailsDialog.vue')['default']
    AccountDialog: typeof import('./src/components/management/AccountDialog.vue')['default']
    AccountsTable: typeof import('./src/components/management/AccountsTable.vue')['default']
    AliasDialog: typeof import('./src/components/management/AliasDialog.vue')['default']
    AliasesTable: typeof import('./src/components/management/AliasesTable.vue')['default']
    AppAvatar: typeof import('./src/@core/components/AppAvatar.vue')['default']
    ApplicationSettingsCard: typeof import('./src/components/management/ApplicationSettingsCard.vue')['default']
    AppLogo: typeof import('./src/@core/components/AppLogo.vue')['default']
    AppModal: typeof import('./src/@core/components/AppModal.vue')['default']
    AuditHistoryCard: typeof import('./src/components/management/AuditHistoryCard.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ConfirmDialog: typeof import('./src/@core/components/ConfirmDialog.vue')['default']
    DeleteConfirmDialog: typeof import('./src/components/management/DeleteConfirmDialog.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    GroupDetailsDialog: typeof import('./src/components/management/GroupDetailsDialog.vue')['default']
    GroupDialog: typeof import('./src/components/management/GroupDialog.vue')['default']
    GroupsTable: typeof import('./src/components/management/GroupsTable.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    NotificationBell: typeof import('./src/components/NotificationBell.vue')['default']
    OidcClientDialog: typeof import('./src/components/management/OidcClientDialog.vue')['default']
    OidcClientsCard: typeof import('./src/components/management/OidcClientsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmtpSettingsCard: typeof import('./src/components/management/SmtpSettingsCard.vue')['default']
    StatsCard: typeof import('./src/components/management/StatsCard.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
  }
}
