# Generated by Django 6.0 on 2025-12-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockspace', '0002_clientaccess_require_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='active', help_text='Account status: active, suspended, or deactivated', max_length=20),
        ),
    ]
