# Generated by Django 6.0 on 2025-12-26 16:24

import dockspace.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockspace', '0003_mailaccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailaccount',
            name='picture',
            field=models.ImageField(blank=True, upload_to=dockspace.core.models.profile_picture_upload_path),
        ),
    ]
