# Generated by Django 6.0 on 2025-12-27 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockspace', '0008_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Device name (e.g., 'iPhone 14', 'Google Authenticator')", max_length=100)),
                ('secret', models.CharField(help_text='TOTP secret key', max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When this device was first verified', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this device was used for authentication', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Django session key', max_length=40)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the client')),
                ('user_agent', models.TextField(help_text='User agent string from the browser')),
                ('browser', models.CharField(blank=True, help_text="Parsed browser name (e.g., 'Chrome on Windows')", max_length=100)),
                ('device', models.CharField(blank=True, help_text='Parsed device name', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Approximate location (city, country)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is still active')),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dockspace_a_created_1923ce_idx',
            old_name='dockspace_a_created_90f5fa_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dockspace_a_actor_i_b3cd2e_idx',
            old_name='dockspace_a_actor_i_0bd3f8_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dockspace_a_action_49689f_idx',
            old_name='dockspace_a_action_a820a0_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dockspace_a_target__589b0f_idx',
            old_name='dockspace_a_target__c3cbe7_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dockspace_a_severit_e868fe_idx',
            old_name='dockspace_a_severit_e59b4d_idx',
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional account data (notification preferences, etc.)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mailgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='totpdevice',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_devices', to='dockspace.mailaccount'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dockspace.mailaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='totpdevice',
            unique_together={('account', 'name')},
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['account', '-last_activity'], name='dockspace_u_account_20f22f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='dockspace_u_session_6a148d_idx'),
        ),
    ]
