# Generated by Django 6.0 on 2025-12-22 06:07

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oidc_provider', '0027_alter_rsakey_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout', models.PositiveIntegerField(default=86400, help_text='Maximum session length in seconds (e.g., 86400 = 24 hours)')),
                ('domain_url', models.URLField(default='http://localhost:8000', help_text='Base domain URL for the application (e.g., https://example.com)', max_length=255)),
                ('smtp_host', models.CharField(blank=True, help_text='SMTP server hostname for outbound email (e.g., smtp.example.com)', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587, help_text='SMTP port (e.g., 587 for STARTTLS, 465 for SSL, 25 for plain)')),
                ('smtp_username', models.CharField(blank=True, help_text='SMTP username if authentication is required', max_length=255)),
                ('smtp_password', models.CharField(blank=True, help_text='SMTP password if authentication is required', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use STARTTLS for SMTP')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Use SSL for SMTP (typically port 465)')),
                ('smtp_from_email', models.EmailField(default='noreply@example.com', help_text='Default From email for outbound messages (e.g., noreply@example.com)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Settings',
                'verbose_name_plural': 'Application Settings',
            },
        ),
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 3-150 chars of letters, numbers, ., _, or -.', regex='^[A-Za-z0-9_.-]{3,150}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(help_text='Given name', max_length=150)),
                ('last_name', models.CharField(help_text='Family name', max_length=150)),
                ('middle_name', models.CharField(blank=True, default='', help_text='Middle name', max_length=150)),
                ('nickname', models.CharField(blank=True, default='', help_text='Nickname', max_length=150)),
                ('profile', models.URLField(blank=True, help_text='Profile URL')),
                ('password_hash', models.CharField(help_text='Value like {SHA512-CRYPT}$6$salt$hash', max_length=255, validators=[django.core.validators.RegexValidator(message='Password hash must include the {SHA512-CRYPT} prefix.', regex='^\\{SHA512-CRYPT\\}.+')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, help_text='Marks the account as a Dockspace admin.')),
                ('phone_number', models.CharField(blank=True, help_text='E.164-ish format, e.g. +15551234567', max_length=50, validators=[django.core.validators.RegexValidator(message='Phone must resemble an E.164 number (e.g. +15551234567).', regex='^\\+?[0-9 .\\-()]{6,20}$')])),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, upload_to='pictures/')),
                ('website', models.URLField(blank=True)),
                ('gender', models.CharField(blank=True, help_text='OIDC gender claim (string)', max_length=50)),
                ('birthdate', models.DateField(blank=True, help_text='YYYY-MM-DD', null=True)),
                ('zoneinfo', models.CharField(blank=True, help_text='IANA time zone, e.g. America/New_York', max_length=50)),
                ('locale', models.CharField(blank=True, help_text='BCP47 locale tag, e.g. en-US', max_length=50, validators=[django.core.validators.RegexValidator(message='Locale must follow BCP47, e.g. en, en-US, fr-CA.', regex='^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$')])),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('locality', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code, uppercase', max_length=2, validators=[django.core.validators.RegexValidator(message='Country must be ISO 3166-1 alpha-2 (e.g. US, CA).', regex='^[A-Z]{2}$')])),
                ('totp_secret', models.CharField(blank=True, max_length=64)),
                ('totp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('totp_last_counter', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['email'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='mailaccount_username_ci_unique'), models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='mailaccount_email_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='MailAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.EmailField(help_text='Alias address exposed to senders', max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_aliases', to='access.mailaccount')),
            ],
            options={
                'verbose_name': 'Mail alias',
                'verbose_name_plural': 'Mail aliases',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='MailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('members', models.ManyToManyField(blank=True, related_name='mail_groups', to='access.mailaccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_access', to='oidc_provider.client')),
                ('groups', models.ManyToManyField(blank=True, related_name='oidc_clients', to='access.mailgroup')),
            ],
            options={
                'verbose_name': 'Client access',
                'verbose_name_plural': 'Client access',
            },
        ),
        migrations.CreateModel(
            name='MailQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_value', models.PositiveIntegerField(default=10, help_text='Numeric quota size, e.g. 10 or 512')),
                ('suffix', models.CharField(choices=[('B', 'Bytes'), ('K', 'KiB'), ('M', 'MiB'), ('G', 'GiB'), ('T', 'TiB')], default='G', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_quota', to='access.mailaccount')),
            ],
            options={
                'ordering': ['user__email'],
                'constraints': [models.CheckConstraint(condition=models.Q(('size_value__gt', 0)), name='mailquota_size_value_gt_0')],
            },
        ),
    ]
